version: '3'

services:
  app:
    container_name: node
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo

  mongo:
    container_name: mongo #for ARM: nonoroazoro/rpi-mongo
    image: mongo:4
    ports:
      - '27017:27017'
    volumes:
      - "db:/data/db"

volumes:
  db:
